### ISSUE TITLE
enhancement of ui and responsiveness

### ISSUE THREAD

**Issue by ROHIT-TECH-UNIVERSE** [AYUSHSINGH24658/Weather-Website#1]
enhancement of the butten and allignment of few items along with a bit enhancement of css and a bit of responsivnesss 
@AYUSHSINGH24658

**Comment by AYUSHSINGH24658** [comment]
You can make changes to your project as per your convenience.
@ROHIT-TECH-UNIVERSE

**Comment by ROHIT-TECH-UNIVERSE** [comment]
@AYUSHSINGH24658 i have made two pull requests one file has css and other has html 
let me know if its okay or not or i ll make the changes

**Comment by AYUSHSINGH24658** [comment]
ok you can make changes

**Comment by ROHIT-TECH-UNIVERSE** [comment]
@AYUSHSINGH24658 you didnt merge my commits is their any issues with it ??please if its so then i am ready to update the things
